// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvfvphyiqhmkqqjgbgmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2ZnZwaHlpcWhta3FxamdiZ21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTk4NzcsImV4cCI6MjA2NTAzNTg3N30.rNghrgFsWqToa0y-AWDdHFVouta0q1807EOloLA7A_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});